FROM openjdk:8-jdk-alpine

ARG kafka_dir=kafka

RUN apk add bash
COPY $kafka_dir /root/kafka
COPY config /root/kafka/config

WORKDIR /root/kafka

ENTRYPOINT ["bin/kafka-server-start.sh", "config/server.properties"]

