version: '3'
services:
  zookeeper:
    image: zookeeper
    ports:
      - '2181:2181'
    build:
      context: .
      dockerfile: Dockerfile_zookeeper
      args:
        kafka_dir: 'kafka_2.11-2.1.0'
  kafka:
    image: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    build:
      context: .
      dockerfile: Dockerfile_kafka
      args:
        kafka_dir: 'kafka_2.11-2.1.0'
  notebook:
    image: jupyter/pyspark-notebook
    ports:
      - '8888-9000:8888'
